language: bash
group: stable
dist: trusty
os: linux
services:
- docker
install:
    - echo "skipping tests"

script:
    - echo "skipping tests"

before_deploy: |-
    # Generate image tags
    export build_tag="${DOCKER_REPO}:${TRAVIS_TAG}-stretch"

    # Build docker image
    docker build \
    --build-arg OPENRESTY_VERSION=${TRAVIS_TAG} \
    -t ${build_tag} \
    .

deploy:
- provider: script
  script:  >-
    docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
    && docker push ${build_tag}
  skip_cleanup: true
  on:
    tags: true
